const GAMES_LIST=[
/* ── PUZZLE ── */
{id:"sudoku",name:"Sudoku",emoji:"🔢",cat:"puzzle",badge:"",url:"/games/sudoku.html"},
{id:"minesweeper",name:"Minesweeper",emoji:"💣",cat:"puzzle",badge:"",url:"/games/minesweeper.html"},
{id:"2048",name:"2048",emoji:"🔢",cat:"puzzle",badge:"hot",url:"/games/2048.html"},
{id:"wordle",name:"Wordle",emoji:"🟩",cat:"puzzle",badge:"hot",url:"/games/wordle.html"},
{id:"freeflow",name:"Flow Free",emoji:"🌊",cat:"puzzle",badge:"",url:"/games/freeflow.html"},
{id:"pipemania",name:"Pipe Mania",emoji:"🔧",cat:"puzzle",badge:"",url:"/games/pipemania.html"},
{id:"hangman",name:"Hangman",emoji:"🪢",cat:"puzzle",badge:"new",url:"/games/hangman.html"},
{id:"sliding-puzzle",name:"Sliding Puzzle",emoji:"🧩",cat:"puzzle",badge:"new",url:"/games/sliding-puzzle.html"},
{id:"word-search",name:"Word Search",emoji:"🔍",cat:"puzzle",badge:"new",url:"/games/word-search.html"},
{id:"towers-of-hanoi",name:"Towers of Hanoi",emoji:"🗼",cat:"puzzle",badge:"new",url:"/games/towers-of-hanoi.html"},
{id:"sokoban",name:"Sokoban",emoji:"📦",cat:"puzzle",badge:"new",url:"/games/sokoban.html"},
{id:"lights-out",name:"Lights Out",emoji:"💡",cat:"puzzle",badge:"new",url:"/games/lights-out.html"},
{id:"mastermind",name:"Mastermind",emoji:"🔐",cat:"puzzle",badge:"new",url:"/games/mastermind.html"},
{id:"anagram",name:"Anagram",emoji:"🔤",cat:"puzzle",badge:"new",url:"/games/anagram.html"},
{id:"word-scramble",name:"Word Scramble",emoji:"📝",cat:"puzzle",badge:"new",url:"/games/word-scramble.html"},
{id:"nim",name:"Nim",emoji:"🏮",cat:"puzzle",badge:"new",url:"/games/nim.html"},
{id:"crossword-mini",name:"Mini Crossword",emoji:"✏️",cat:"puzzle",badge:"new",url:"/games/crossword-mini.html"},
{id:"number-sequence",name:"Number Sequence",emoji:"🔢",cat:"puzzle",badge:"new",url:"/games/number-sequence.html"},
{id:"maze",name:"Maze",emoji:"🌀",cat:"puzzle",badge:"new",url:"/games/maze.html"},
{id:"pipe-puzzle",name:"Pipe Puzzle",emoji:"🔧",cat:"puzzle",badge:"new",url:"/games/pipe-puzzle.html"},

/* ── ARCADE ── */
{id:"snake",name:"Snake",emoji:"🐍",cat:"arcade",badge:"hot",url:"/games/snake.html"},
{id:"tetris",name:"Tetris",emoji:"🧱",cat:"arcade",badge:"hot",url:"/games/tetris.html"},
{id:"breakout",name:"Breakout",emoji:"🧱",cat:"arcade",badge:"",url:"/games/breakout.html"},
{id:"spaceinvaders",name:"Space Invaders",emoji:"👾",cat:"arcade",badge:"",url:"/games/spaceinvaders.html"},
{id:"asteroids",name:"Asteroids",emoji:"☄️",cat:"arcade",badge:"",url:"/games/asteroids.html"},
{id:"dino",name:"Dino Run",emoji:"🦕",cat:"arcade",badge:"",url:"/games/dino.html"},
{id:"flappy",name:"Flappy Bird",emoji:"🐦",cat:"arcade",badge:"",url:"/games/flappy.html"},
{id:"pong",name:"Pong",emoji:"🏓",cat:"arcade",badge:"",url:"/games/pong.html"},
{id:"pac-man",name:"Pac-Man",emoji:"👻",cat:"arcade",badge:"new",url:"/games/pac-man.html"},
{id:"frogger",name:"Frogger",emoji:"🐸",cat:"arcade",badge:"new",url:"/games/frogger.html"},
{id:"galaga",name:"Galaga",emoji:"🚀",cat:"arcade",badge:"new",url:"/games/galaga.html"},
{id:"bubble-shooter",name:"Bubble Shooter",emoji:"🫧",cat:"arcade",badge:"new",url:"/games/bubble-shooter.html"},
{id:"whack-a-mole",name:"Whack-a-Mole",emoji:"🦔",cat:"arcade",badge:"new",url:"/games/whack-a-mole.html"},
{id:"balloon-pop",name:"Balloon Pop",emoji:"🎈",cat:"arcade",badge:"new",url:"/games/balloon-pop.html"},
{id:"platformer",name:"Platformer",emoji:"🎮",cat:"arcade",badge:"new",url:"/games/platformer.html"},
{id:"endless-runner",name:"Endless Runner",emoji:"🏃",cat:"arcade",badge:"new",url:"/games/endless-runner.html"},
{id:"pinball",name:"Pinball",emoji:"⚪",cat:"arcade",badge:"new",url:"/games/pinball.html"},
{id:"fruit-catcher",name:"Fruit Catcher",emoji:"🍎",cat:"arcade",badge:"new",url:"/games/fruit-catcher.html"},
{id:"stack-tower",name:"Stack Tower",emoji:"🏗️",cat:"arcade",badge:"new",url:"/games/stack-tower.html"},
{id:"shooting-gallery",name:"Shooting Gallery",emoji:"🎯",cat:"arcade",badge:"new",url:"/games/shooting-gallery.html"},
{id:"coin-collector",name:"Coin Collector",emoji:"🪙",cat:"arcade",badge:"new",url:"/games/coin-collector.html"},
{id:"air-hockey",name:"Air Hockey",emoji:"🏒",cat:"arcade",badge:"new",url:"/games/air-hockey.html"},
{id:"brick-breaker-2",name:"Brick Breaker Deluxe",emoji:"🧱",cat:"arcade",badge:"new",url:"/games/brick-breaker-2.html"},

/* ── CARD & BOARD ── */
{id:"chess",name:"Chess",emoji:"♟️",cat:"board",badge:"",url:"/games/chess.html"},
{id:"connect4",name:"Connect 4",emoji:"🔴",cat:"board",badge:"",url:"/games/connect4.html"},
{id:"tictactoe",name:"Tic Tac Toe",emoji:"❌",cat:"board",badge:"",url:"/games/tictactoe.html"},
{id:"blackjack",name:"Blackjack",emoji:"🃏",cat:"card",badge:"",url:"/games/blackjack.html"},
{id:"solitaire",name:"Solitaire",emoji:"🂡",cat:"card",badge:"new",url:"/games/solitaire.html"},
{id:"checkers",name:"Checkers",emoji:"⚫",cat:"board",badge:"new",url:"/games/checkers.html"},
{id:"reversi",name:"Reversi",emoji:"⬛",cat:"board",badge:"new",url:"/games/reversi.html"},
{id:"battleship",name:"Battleship",emoji:"🚢",cat:"board",badge:"new",url:"/games/battleship.html"},
{id:"mancala",name:"Mancala",emoji:"🏮",cat:"board",badge:"new",url:"/games/mancala.html"},
{id:"card-war",name:"Card War",emoji:"🃏",cat:"card",badge:"new",url:"/games/card-war.html"},
{id:"video-poker",name:"Video Poker",emoji:"♠️",cat:"card",badge:"new",url:"/games/video-poker.html"},
{id:"dots-and-boxes",name:"Dots & Boxes",emoji:"🔲",cat:"board",badge:"new",url:"/games/dots-and-boxes.html"},
{id:"yahtzee",name:"Yahtzee",emoji:"🎲",cat:"board",badge:"new",url:"/games/yahtzee.html"},
{id:"mahjong-solitaire",name:"Mahjong Solitaire",emoji:"🀄",cat:"board",badge:"new",url:"/games/mahjong-solitaire.html"},
{id:"ludo",name:"Ludo",emoji:"🎲",cat:"board",badge:"",url:"/games/ludo.html"},
{id:"snake_ladder",name:"Snake & Ladder",emoji:"🐍",cat:"board",badge:"",url:"/games/snake_ladder.html"},

/* ── SPORTS & CASINO ── */
{id:"basketball",name:"Basketball",emoji:"🏀",cat:"sports",badge:"new",url:"/games/basketball.html"},
{id:"darts",name:"Darts",emoji:"🎯",cat:"sports",badge:"new",url:"/games/darts.html"},
{id:"mini-golf",name:"Mini Golf",emoji:"⛳",cat:"sports",badge:"new",url:"/games/mini-golf.html"},
{id:"penalty-kick",name:"Penalty Kick",emoji:"⚽",cat:"sports",badge:"new",url:"/games/penalty-kick.html"},
{id:"pool-billiards",name:"8-Ball Pool",emoji:"🎱",cat:"sports",badge:"new",url:"/games/pool-billiards.html"},
{id:"craps",name:"Craps",emoji:"🎲",cat:"casino",badge:"new",url:"/games/craps.html"},
{id:"roulette",name:"Roulette",emoji:"🎡",cat:"casino",badge:"new",url:"/games/roulette.html"},
{id:"slot-machine",name:"Slot Machine",emoji:"🎰",cat:"casino",badge:"new",url:"/games/slot-machine.html"},
{id:"blackjack-pro",name:"Blackjack Pro",emoji:"♠️",cat:"casino",badge:"new",url:"/games/blackjack-pro.html"},
{id:"bowling",name:"Bowling",emoji:"🎳",cat:"sports",badge:"new",url:"/games/bowling.html"},

/* ── CASUAL & MATCH ── */
{id:"memory",name:"Memory Match",emoji:"🧠",cat:"casual",badge:"",url:"/games/memory.html"},
{id:"simon",name:"Simon Says",emoji:"🔴",cat:"casual",badge:"",url:"/games/simon.html"},
{id:"cookie",name:"Cookie Clicker",emoji:"🍪",cat:"casual",badge:"hot",url:"/games/cookie.html"},
{id:"color-sequence",name:"Color Sequence",emoji:"🔴",cat:"casual",badge:"new",url:"/games/color-sequence.html"},
{id:"reaction-test",name:"Reaction Test",emoji:"⚡",cat:"casual",badge:"new",url:"/games/reaction-test.html"},
{id:"paint",name:"Digital Paint",emoji:"🎨",cat:"casual",badge:"new",url:"/games/paint.html"},
{id:"gem-swap",name:"Gem Swap",emoji:"💎",cat:"casual",badge:"new",url:"/games/gem-swap.html"},
{id:"color-flood",name:"Color Flood",emoji:"🌊",cat:"casual",badge:"new",url:"/games/color-flood.html"},
{id:"color-sort",name:"Color Sort",emoji:"🧪",cat:"casual",badge:"new",url:"/games/color-sort.html"},
{id:"color-match",name:"Color Match",emoji:"🎨",cat:"casual",badge:"new",url:"/games/color-match.html"},
{id:"match-3",name:"Match 3",emoji:"⭐",cat:"casual",badge:"new",url:"/games/match-3.html"},

/* ── EDUCATIONAL ── */
{id:"math-duck",name:"Math Duck",emoji:"🦆",cat:"educational",badge:"",url:"/games/math-duck.html"},
{id:"mathrace",name:"Math Race",emoji:"🏎️",cat:"educational",badge:"",url:"/games/mathrace.html"},
{id:"fractions",name:"Fractions",emoji:"½",cat:"educational",badge:"",url:"/games/fractions.html"},
{id:"multiplication",name:"Multiplication",emoji:"✖️",cat:"educational",badge:"",url:"/games/multiplication.html"},
{id:"numberbomb",name:"Number Bomb",emoji:"💥",cat:"educational",badge:"",url:"/games/numberbomb.html"},
{id:"typing",name:"Typing Speed",emoji:"⌨️",cat:"educational",badge:"",url:"/games/typing.html"},
{id:"trivia-quiz",name:"Trivia Quiz",emoji:"🧠",cat:"educational",badge:"new",url:"/games/trivia-quiz.html"},
{id:"math-quiz",name:"Math Quiz",emoji:"➕",cat:"educational",badge:"new",url:"/games/math-quiz.html"},
{id:"spelling-bee",name:"Spelling Bee",emoji:"🐝",cat:"educational",badge:"new",url:"/games/spelling-bee.html"},
{id:"number-guess",name:"Number Guess",emoji:"🔢",cat:"educational",badge:"new",url:"/games/number-guess.html"},
{id:"word-chain",name:"Word Chain",emoji:"🔗",cat:"educational",badge:"new",url:"/games/word-chain.html"},
{id:"addition-race",name:"Addition Race",emoji:"🏁",cat:"educational",badge:"new",url:"/games/addition-race.html"},
{id:"multiplication-grid",name:"Multiplication Grid",emoji:"✖️",cat:"educational",badge:"new",url:"/games/multiplication-grid.html"},
{id:"towerdefense",name:"Tower Defense",emoji:"🏰",cat:"strategy",badge:"",url:"/games/towerdefense.html"},
];
